name: build-and-deploy
on: 
  push:
    branches:
      - master

  schedule:
    - cron: '0 * * * *' # run on every hour

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: pip install -r requirements.txt
      

      - name: Crawling
        run: python3 src/main.py

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: data # The branch the action should deploy to.
          folder: data # The folder the action should deploy.