name: build-and-deploy
on: 
  push:
    branches:
      - master

  schedule:
    - cron: '0 6 * * 0,3' # run on every 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: pip install -r requirements.txt
      

      - name: Crawling
        run: python3 src/main.py

      - name: Upload Course
        env: 
          db_username: ${{ secrets.DATABASE_USERNAME }}
          db_password: ${{ secrets.DATABASE_PASSWORD }}
          db_host: ${{ secrets.DATABASE_HOST }}
          db_port: ${{ secrets.DATABASE_PORT }}
        run: |
          mysql app --local-infile=1 --execute "DELETE FROM COURSE" -u "$db_username" -h "$db_host" -p"$db_password"
          DIR=$"./data"
          files=($(find $DIR -name "*course.csv"))
          len=${#files[@]}
          for (( i=0; i<$len; i++ )); 
          do  
            mysql app --local-infile=1 -u "$db_username" -h "$db_host" -p"$db_password" -P "$db_port" --execute "LOAD DATA LOCAL INFILE '${files[$i]}' 
            INTO TABLE COURSE FIELDS TERMINATED BY ',' 
            ENCLOSED BY '\"' LINES 
            TERMINATED BY '\n' 
            IGNORE 1 ROWS" 
          done

      - name: Upload Seat
        env: 
          db_username: ${{ secrets.DATABASE_USERNAME }}
          db_password: ${{ secrets.DATABASE_PASSWORD }}
          db_host: ${{ secrets.DATABASE_HOST }}
          db_port: ${{ secrets.DATABASE_PORT }}    
        run: |
          mysql app --local-infile=1 --execute "DELETE FROM SEAT" -u "$db_username" -h "$db_host" -p"$db_password"
          DIR=$"./data"
          files=($(find $DIR -name "*seat.csv"))
          len=${#files[@]}
          for (( i=0; i<$len; i++ )); 
          do  
            mysql app --local-infile=1 -u "$db_username" -h "$db_host" -p"$db_password" -P "$db_port" --execute "LOAD DATA LOCAL INFILE '${files[$i]}' 
            INTO TABLE SEAT FIELDS TERMINATED BY ',' 
            ENCLOSED BY '\"' LINES 
            TERMINATED BY '\n' 
            IGNORE 1 ROWS" 
          done

        
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: data # The branch the action should deploy to.
          folder: data # The folder the action should deploy.
